# Generated by Django 4.1.7 on 2023-02-25 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_taken',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
