# Generated by Django 4.1.7 on 2023-02-25 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_end_time_team_start_time_alter_team_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_taken',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
