# Generated by Django 4.1.7 on 2023-02-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_team_end_time_alter_team_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_time',
        ),
    ]
