# Generated by Django 4.1.7 on 2023-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_team_end_time_remove_team_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
