# Generated by Django 4.1.7 on 2023-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_level_team_real_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='real_end_time',
            field=models.IntegerField(default=7200984147),
        ),
    ]
