# Generated by Django 4.1.7 on 2023-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_real_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='real_end_time',
            field=models.IntegerField(default=7200670569),
        ),
    ]
